language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - cd udagram-api/feed && docker build -t udagram-feed . && cd ..
  - docker tag udagram-feed ankugarg580/udagram-feed:latest
  - cd users && docker build -t udagram-users . && cd .. && cd ..
  - docker tag udagram-users ankugarg580/udagram-users:latest
  - cd udagram-frontend && docker build -t udagram-frontend . && cd ..
  - docker tag udagram-frontend ankugarg580/udagram-frontend:latest
  - cd reverse-proxy && docker build -t reverse-proxy .
  - docker tag reverse-proxy ankugarg580/reverse-proxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ankugarg580/udagram-users
  - docker push ankugarg580/udagram-feed
  - docker push ankugarg580/udagram-frontend
  - docker push ankugarg580/reverse-proxy