apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-microservice
  labels:
    app: users-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-microservice
  template:
    metadata:
      labels:
        app: users-microservice
    spec:
      containers:
      - name: udagram-users
        image: ankugarg580/udagram-users
        ports:
        - containerPort: 8080